language: csharp
solution: Paramulate.sln
install:
  - nuget restore Paramulate.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release Paramulate.sln
  - nunit-console ./Paramulate.Test/bin/Release/Paramulate.Test.dll
